### PR TITLE
Inline (with base64 data-uri) externally linked images and resolved path fix

### PR DESCRIPTION
**Pull request by liuq**
I succeeded in inlining also externally linked images (with ad-hoc code). Now they are rendered in a data:base64 uri that is inlined in the markdown (and eventually in the remark.js generated html).

Moreover, I fixed relative paths for export also in html template and sass style (if they do not need to be inlined).

The only added dependency is mime, which is already included by inliner. I didn't make it explicit in the package.json file, so feel free to do it.

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for the PR!

I have a few questions on this:
- It only inline local images (`file://`) images from the markdown, right?
- Why manually inline images/css in HTML? It should be taken care of by [inliner](https://github.com/remy/inliner)?

**Comment by liuq** [comment]
In principle it downloads and inlines any kind of url (besides data:). Moreover, as for the \ images in the markdown, if the source is included as a string in the call to remark.create(), inliner ignores it.

**Comment by sinedied** [comment]
> In principle it downloads and inlines any kind of url (besides data:).

Did you try it with http resources? I think that `fs.readFileSync` only works with local files, not HTTP urls.

**Comment by liuq** [comment]
No, I admit I didn't. I will check whether it works also with http URLs but in case I will switch to the asynchronous file read (adapting the code).

If it is ok with you I will first proceed with sync including only file:/// urls and then I will take care of http.

**Comment by liuq** [comment]
Apparently it will not work with http urls, therefore I changed the regular expression so that now only images having file:/// urls will be inlined.

**Comment by sinedied** [comment]
Perfect!
By the way, you should add the email used in your git config to github (additional email adresses), so you can be listed on the project contributors list if you like. 😉

**Comment by liuq** [comment]
I did it, now I listed it on github config. :-)

Next PR of mine will include also the inline inclusion of external (http) Images! Keep in touch!

**Comment by sinedied** [comment]
If found an edge case on this, when using CSS or Remark statements directly in the markdown files (like `background-image: url(./img/img.gif)`) the images are not inlined. This should be easy to fix as the code is already there :)

**Comment by sinedied** [comment]
I just fixed that edge case and published a new `2.3.0` version with your changes.

**Pull request merged**
